Hero Block changes wrt to desktop and mobile images
aemsites/stericycle-shared pull request #535
Opened 2024-11-21 07:20 UTC by jindaliiita

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #527 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.live/drafts/piyush/en-us
  - https://main--shredit--stericycle.aem.live/en-us
- After: 
  - https://hero-block-changes--shredit--stericycle.aem.live/drafts/piyush/en-us
  - https://hero-block-changes--shredit--stericycle.aem.live/en-us

2024-11-21 13:36 UTC, colinvlasak commented
@jindaliiita this looks good. How do we configure this for authoring? 
Is it just that top image is always mobile and the second image is always desktop? 
If we don't add mobile image does it just crop the desktop image as it has been? 
Will this Hero block style be applied to all pages or something we would add manually to pages that need a separate mobile image?

2024-11-22 17:09 UTC, jindaliiita commented
@MarquiseRosier @bstopp can you please review this ?

2024-11-22 17:11 UTC, bstopp requested changes

2024-11-22 17:11 UTC, bstopp commented on blocks/hero/hero.js
> +      tempPic = createOptimizedPicture(
Don't use createOptimizedPicture - we have an optimzied picture. Just use it and if needed clone the DOM.

2024-11-22 17:12 UTC, bstopp commented on blocks/hero/hero.js
> +      tempPic = createOptimizedPicture(
The only time you should need to use `createOptimizedPicture` is if you have a URL reference to an image that you have to fetch - if the image reference is coming from the server as part of the block/page markup, it is already optimized, and has more data (i.e. dimensions) than this function can provide.

2024-11-22 19:43 UTC, bstopp requested changes

2024-11-22 19:43 UTC, bstopp commented on blocks/hero/hero.css
> +      display: unset;
This should be `display: block` - otherwise it's gets confusing as to how it derives its state.

2024-11-22 19:43 UTC, bstopp commented on scripts/scripts.js
> +  if (document.querySelector('body.blog-page') || document.querySelector('.hero')) {
May want to be more specific here on this selector, given that none of the sections or block decoration has happened yet.
```suggestion
  if (document.querySelector('body.blog-page') || document.querySelector(':scope > div > div.hero')) {
```

2024-11-22 19:43 UTC, bstopp commented on blocks/hero/hero.css
> +  & picture.hero-background.mobile-only {
You can probably just move the declaration in the 992px breakpoint to here, then swap out the mobile/desktop display state to based on breakpoint. That way you only declare the picture/image css once.

2024-11-25 14:38 UTC, bstopp approved these changes

2024-11-25 14:38 UTC, merged