add xxxl icon
aemsites/stericycle-shared pull request #669
Opened 2024-12-23 11:23 UTC by MarquiseRosier

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/
- After: 
  - https://<branch>--shredit--stericycle.aem.page/

2024-12-23 14:26 UTC, kronnox requested changes

2024-12-23 14:26 UTC, kronnox commented on styles/styles.css
> +}
That should be part of the columns stylesheet. Is it really needed though? Normally the `img` within the icon `span` should auto scale to it. Other than that LGTM

2025-01-01 18:01 UTC, MarquiseRosier commented on styles/styles.css
> +}
this is resolved. 

Also; hypothetically yes; but if you review the codebase; you'll see this effects the tag. 

https://github.com/aemsites/stericycle-shared/blob/fc972053ff1f22c887f7954ae7ff9367042d33b2/blocks/columns/default.css#L65-L68

so i'll just exempt this block from that styling for now; but this obviously needs to be addressed in the futuer.

2025-01-08 09:44 UTC, kronnox approved these changes
Otherwise LGTM

2025-01-08 09:44 UTC, kronnox commented on blocks/columns/default.css
> +main .columns:not(.xxxl-icons) span.icon > img {
nit: I would argue it makes sense to add all the icon size classes here for consistency ;)

2025-01-09 13:48 UTC, merged